name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.*
      - name: Configure committer
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
      - name: npm install, build, and release
        run: |
          npm ci
          npx standard-version
          git push --follow-tags
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
