name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.13.2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.*
          cache: pnpm
      - name: Configure committer
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
      - name: npm install, build, and release
        run: |
          pnpm i --frozen-lockfile
          pnpx standard-version
          npm publish
          git push --follow-tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
