name: release

on:
  push:
    branches: [test]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.*
      - name: npm install, build, and release
        run: |
          npm ci
          npx standard-version --dry-run
        env:
          CI: true
